### ISSUE TITLE
The "How to deploy a server to GameLift" part of the README doesn't make sense

### ISSUE THREAD

**Issue by herpdederp** [aws-samples/amazon-gamelift-unity#2]
It isn't clear how or why to create an IAM user, or how to download a credentials file. 

In addition, the "C:\dev\GameLiftUnity\Build\deploy.bat 25.0" command results in "Error occurred. Message:'The specified location-constraint is not valid' when writing an object"

**Comment by alanmur** [comment]
Thank you for your feedback!
Readme.md has improved information on this topic.
Error creating a build bucket has been fixed.

Al Murray :)

**Comment by herpdederp** [comment]
I am still getting the "Error occurred. Message:'The specified location-constraint is not valid' when writing an object" after pulling the most recent changes

**Comment by alanmur** [comment]
Please run clean.bat, then try again.
